driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.0.3
  data_path: test/shared

platforms:
  - name: centos-6.7
    driver: 
      vagrantfile_erb: Vagrantfile.erb
    run_list:
      - recipe[yum::default]
  - name: centos-7.2
    driver: 
      vagrantfile_erb: Vagrantfile.erb
    run_list:
      - recipe[yum::default]

suites:
  - name: default
    run_list:
        - recipe[supervisor::default]
        - recipe[prometheus::default]
        - recipe[prometheus::alertmanager]
    attributes:
      prometheus:
        install_method: binary
        init_style: supervisor
        checksum: 0a0e301a2f166a52a4e870f1f83e7a6bee3783d7ce35c7ba34f1d2f20a78cbd8
        binary_url: https://github.com/prometheus/prometheus/releases/download/0.17.0/prometheus-0.17.0.linux-amd64.tar.gz

