driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.0.3
  data_path: test/shared

platforms:
  - name: centos-6.7
    driver: 
      vagrantfile_erb: Vagrantfile.erb
    run_list:
      - recipe[yum::default]
  - name: centos-7.2
    driver: 
      vagrantfile_erb: Vagrantfile.erb
    run_list:
      - recipe[yum::default]

suites:
  - name: default
    run_list:
        - recipe[supervisor::default]
        - recipe[prometheus::default]
        - recipe[prometheus::alertmanager]
    attributes:
      prometheus:
        install_method: binary
        init_style: supervisor
        checksum: 0511576f19ff060712d19fb343957113f6a47b2d2edcbe4889eaaa844b31f516
        binary_url: https://chefresources.ncredinburgh.com/prometheus/prometheus-1.4.1.linux-amd64.tar.gz
        alertmanager:
          package_url: https://chefresources.ncredinburgh.com/prometheus/alertmanager-0.5.1.linux-amd64.tar.gz
          package_checksum: 9df9f0eb0061c8ead1b89060b851ea389fbdf6c1adc8513b40f6f4b90f4de932

